### PR TITLE
Ukrainian koi8u char freq. tab + language model

### PR DESCRIPTION
**Pull request by Alter-1**
language/charset detector doesn't contain KOI8-U frequency table and Ukrainian language model, those are different from KOI8-R
There are several specific letters and apostrophe inside words.
New frequency table is generated (see http://alter.org.ua/docs/other/ua_langmodel for details)
both original koi8r and new koi8u were tested on Russian and Ukrainian KOI8 files and could distinguish between them

### CODE REVIEW

**Comment by yhfudev** [comment]
Can  you please add test files in the folder test/ru ?

**Comment by Alter-1** [comment]
Ok, I'll do it. But would it be better to place it under 
test/ua/KOI8-U ?

**Comment by yhfudev** [comment]
It looks fine for me.
Please add the files and I can merge to the repo. thanks!

**Comment by Alter-1** [comment]
I've added KOI8-U test file

**Comment by yhfudev** [comment]
I tested the patch, I got
```bash
utils/ucd test/ua/KOI8-U
'ucd' detected charset encoding: 'KOI8-R'!
KOI8-R
```

**Comment by Alter-1** [comment]
test file is added

**Comment by Alter-1** [comment]
ok, I would re-test

**Comment by Alter-1** [comment]
Really. Charsets are very close. Also, there was a bug with indexing in koi8u charToOrderMap (0-based instead of 1-based)
I've rebuild both koi8-r and koi8-u models with ~2Mb sample files. (added --apostrophe option to mkpairmodel.py to handle Ukrainian text properly)
And I had to add special case for koi8u vs koi8r check in nsSBCSGroupProber::HandleData - here we should check both variants and chose best matching.

**Comment by yhfudev** [comment]
Great job! Thank you.

**Pull request merged**
